import numpy as np

a = np.array([0,30,45,60,90])
sin = np.sin(a*np.pi/180)
print ('正弦值：')
print (sin)
print ('利用正弦值計算角度，返回值以弧度為單位：')
inv = np.arcsin(sin)
print (inv)
print ('轉換為角度：')
print (np.degrees(inv))
print ('餘弦值：')
cos = np.cos(a*np.pi/180)
print (cos)
print ('利用餘弦值計算角度，返回值以弧度為單位：')
inv = np.arccos(cos)
print (inv)
print ('轉換為角度：')
print (np.degrees(inv))
print ('正切值：')
tan = np.tan(a*np.pi/180)
print (tan)
print ('利用正切值計算角度，返回值以弧度為單位：')
inv = np.arctan(tan)
print (inv)
print ('轉換為角度：')
print (np.degrees(inv))

