import numpy as np

a = np.array([[10, 20, 30], [50, 30, 10], [70, 40, 20]])
print('陣列數值為：')
print(a)
print('使用 argmax() 函數：')
print(np.argmax(a))
print('展平陣列：')
a1 = a.flatten()
print('使用 argmax() 函數：')
print(np.argmax(a1))
print('沿軸 0 的最大值索引：')
maxindex = np.argmax(a, axis=0)
print(maxindex)
print('沿軸 1 的最大值索引：')
maxindex = np.argmax(a, axis=1)
print(maxindex)
print('使用 argmin() 函數：')
minindex = np.argmin(a)
print(minindex)
print('沿軸 0 的最小值索引：')
minindex = np.argmin(a, axis=0)
print(minindex)
print('沿軸 1 的最小值索引：')
minindex = np.argmin(a, axis=1)
print(minindex)

